### ISSUE TITLE
DTSGInitialData

### ISSUE THREAD

**Issue by 89z** [duckimann/tempaste#1]
how to get this:

https://github.com/duckimann/tempaste/blob/2f95670b9b7e44743cbda780cac4d27e82ab84d5/facebook/getVid.js#L8

**Comment by duckimann** [comment]
Wdym "how to get this"?

**Comment by 89z** [comment]
the code is calling this value:

~~~
require("DTSGInitialData").token
~~~

but that value is not defined anywhere in this repo

**Comment by duckimann** [comment]
Ah, that DTSGInitalData belongs to the facebook itself, you can see it in some js file used by facebook.
